### ISSUE TITLE
error: Unknown slot type 'LIGHTS' for slot 'Lights' 

### ISSUE THREAD

**Issue by leoizbicki** [sarkonovich/Alexa-Hue#15]
"Now, for the custom slot values "LIGHTS" and "SCENES" substitute in the appropriate values for your lights and scenes."

How do we alter custom_slots? Do we remove LIGHTS and replace it with something else, or do we remove entries under LIGHTS that aren't applicable (fireplace lights, etc)?

Thanks!

**Comment by sarkonovich** [comment]
Hey there!

In the developers portal, under "Interaction Model" (where you add the
sample utterances and intent schema), you'll see a section called "Custom
Slot Types."
You click on "Add Slot Type", name it LIGHTS, and add the names of your
lights there. Then you do the same for a new custom slot "SCENES."

Does that make sense?

Steve

**Comment by leoizbicki** [comment]
Hello!

yes, that makes sense! Sorry I misinterpreted that. Now I am stuck on
saving after I've added intents, slots, and utterances. I get the following
error: Error: There was an unknown failure building the intent schema.

Thoughts?

**Comment by sarkonovich** [comment]
I think that's an Amazon problem. It crops up from time to time. I'd try
again later. If it's still happening after a day, let me know and I'm more
than happy to troubleshoot.

Steve
