### ISSUE TITLE
Alexa Cannot Find Light

### ISSUE THREAD

**Issue by bjt63** [sarkonovich/Alexa-Hue#19]
Hi,

I have been trying to get this working for a few days now.  Am not sure if this is the right forum so apologies if I am asking in the wrong place.

I have followed instructions but continually end at the same point.

I can ask Alexa to list the lights and she sends a card to the alexa app with all my lights, so I know it can see my lights.

But when I ask her to perform an action she continually replies with the same response 
If I ask Alexa to "Alexa ask lighting to turn rose light blue"
The response I get back is;
"Please specify which light you would like to adjust I am ready to control the lights"
Unfortunately re-specifying a light makes no difference she just repeats the above.

In debugging it I have bypassed ngrok and have AWS talking directly to my server
ie
'amzn1.echo-sdk-ams.app.c26243f9-2294-4f16-8b07-ad9ee1b7afe7':'http://cool.no-ip.net:4567/lights'

I have my server running docker (ubuntu 16.04 on Hp Microserver )  port 4567 open to internet

I have had docker pull image sarkonovich/docker-alexa-hue

My Server Started by

"docker run -e "TZ=Australia/Melbourne" -itdP --net=host --name=docker-alexa-hue sarkonovich/docker-alexa-hue"

from docker ps

CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                  PORTS               NAMES
25c9cfe1685a        sarkonovich/docker-alexa-hue   "/bin/sh -c '/bin/bas"   46 minutes ago      Up 46 minutes                               docker-alexa-hue

output from docker-alexa-hue image

root@phobos:~/hue/Alexa-Hue# docker logs 25c9cfe1685a 
[2016-07-18 18:18:55] INFO  WEBrick 1.3.1
[2016-07-18 18:18:55] INFO  ruby 2.2.4 (2015-12-16) [x86_64-linux]
== Sinatra (v1.4.7) has taken the stage on 4567 for production with backup from WEBrick
[2016-07-18 18:18:55] INFO  WEBrick::HTTPServer#start: pid=1 port=4567
ec2-54-87-208-204.compute-1.amazonaws.com - - [18/Jul/2016:18:30:11 AEST] "POST /lights HTTP/1.1" 200 361
- -> /lights
  ec2-54-87-208-204.compute-1.amazonaws.com - - [18/Jul/2016:18:31:02 AEST] "POST /lights HTTP/1.1" 200 352
- -> /lights
  ec2-54-87-208-204.compute-1.amazonaws.com - - [18/Jul/2016:18:33:33 AEST] "POST /lights HTTP/1.1" 200 276
- -> /lights
  ec2-54-87-208-204.compute-1.amazonaws.com - - [18/Jul/2016:18:33:45 AEST] "POST /lights HTTP/1.1" 200 276
- -> /lights
  ec2-54-87-208-204.compute-1.amazonaws.com - - [18/Jul/2016:18:33:55 AEST] "POST /lights HTTP/1.1" 200 276
- -> /lights
  ec2-54-87-208-204.compute-1.amazonaws.com - - [18/Jul/2016:18:34:08 AEST] "POST /lights HTTP/1.1" 200 276
- -> /lights
  ec2-54-87-208-204.compute-1.amazonaws.com - - [18/Jul/2016:18:34:17 AEST] "POST /lights HTTP/1.1" 200 276
- -> /lights
  ec2-54-87-208-204.compute-1.amazonaws.com - - [18/Jul/2016:18:34:29 AEST] "POST /lights HTTP/1.1" 200 200
- -> /lights
  ec2-54-87-208-204.compute-1.amazonaws.com - - [18/Jul/2016:18:35:11 AEST] "POST /lights HTTP/1.1" 200 276
- -> /lights

Any help or pointers would be greatful

Thanks 
Brian T.

**Comment by sarkonovich** [comment]
Hmm...everything is setup correctly at the server end. So, I'd expect it has to do with the sample utterances provided. (Maybe.) Is this the exact error message you're getting,  "Please specify which light or lights you'd like to adjust. I'm ready to control the lights."?

In the sample utterances in the developer console, make sure that the custom slot type "LIGHTS" has the following entry:

`rose light`

assuming that "rose" is the name of a single bulb.

If that doesn't help, we'll dig deeper.

**Comment by bjt63** [comment]
Legend - Yep that fixed it. 
Thanks soooo much for your help and of course the skill 
One more question is there any way to add authentication to the server without using ngrok?

Now where's your donate button?

Thanks Again
Brian T.

**Comment by sarkonovich** [comment]
Great!  Glad it works! (No donate button, but not a bad idea!)
