### ISSUE TITLE
Testing the server.

### ISSUE THREAD

**Issue by harrypottar** [sarkonovich/Alexa-Hue#21]
I have followed the Raspberry Pi3 without docker instructions.

I have started the app in the background ruby ./app.rb &

When ever I try and test on my ocal connection in the browser I get connection refused.
192.168.1.201:4567/lights

I did not install docker nor ngrok, I have a static IP and can port forward from my router.

I also have a LAMP server running on this same install and that accesses fine. I have never used ruby so not sure where to go from here.
Thanks

**Comment by sarkonovich** [comment]
Hello!

What is the message that the sinatra server throws when you test -- can you
see the output?

I wouldn't expect it to work, since (I'm guessing) you're sending a GET
request in the browser and the server is expecting a POST request.
Have you tried using an Alexa device?  What happens if you do?

Steve

**Comment by harrypottar** [comment]
HI Steve,

Thanks for getting back to me so quickly

This is the output form the Raspberry PI

ruby ./app.rb &
[1] 20326
pi@raspberrypi:/var/www/html/Alexa-Hue-master $ [2016-08-27 21:44:23] INFO  WEBrick 1.3.1
[2016-08-27 21:44:23] INFO  ruby 2.3.0 (2015-12-25) [armv7l-linux-eabihf]
== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from WEBrick
[2016-08-27 21:44:23] INFO  WEBrick::HTTPServer#start: pid=20326 port=4567

I try and browse to that location on my local network, 

http://192.168.1.201:4567/lights

I get

This site can’t be reached

192.168.1.201 refused to connect.

I added a port forwarding rule to my router to forward port 80 on my static ip to port 4567 on the Raspberry PI

If I test through Alexa I get these errors from Lambda

  "errorMessage": "No url found for application id”

"errorMessage": "Exception: TypeError: Parameter 'url' must be a string, not undefined"

However I have correctly filled out the line 9 of the node js.

var handlers = {
            'appId':'url',
            'amzn1.echo-sdk-ams.app.e4c60f63-cac6-4206-82ae-XXXXXXXX':'http://XXXXXXXXX/lights'
        };

X’s have the full id and my external ip

I wanted to see if there was a way to test the Raspberry PI on the internal network first make sure that is running then fix the connection issue.

Thanks in advanced

Harry

**Comment by sarkonovich** [comment]
I think this is a sinatra setup problem, since you aren't using ngrok. Add
the following line to app.rb

set :bind, '0.0.0.0'

You can just put it above the 'set :protection....' line
restart the server, and try to access it again. You should get a message
like, "Sinatra doesn't know this ditty" (because you are sending a GET
request.)

Let me know if that works...then we can figure out what's going on with
Lambda.

Steve

**Comment by harrypottar** [comment]
HI Steve,

Sorry had to run out and pick the kids up.

Once again thank you for your help.

Adding the set bind fixed the server I can not test the server on the local network, thanks you.

When I ask Alexa to list my light, I get the message about pressing the button on the bridge and launch the skill again.

When I do I get a bad response.

SyntaxError: Unexpected token < at Object.parse (native) at IncomingMessage.<anonymous> (/var/task/index.js:42:38) at IncomingMessage.emit (events.js:117:20) at _stream_readable.js:944:16 at process._tickCallback (node.js:448:13)

Thanks 

Harry

**Comment by sarkonovich** [comment]
Where is that error message coming from...the sinatra server??

**Comment by harrypottar** [comment]
HI Steve,

Yes it looks like its the response sent back, I’m looking at the logs in clod watch.

It only happens if I press the hue bridge button, otherwise I can ask it anything and it comes bad telling me to press the bridge button.

Thanks
harry

**Comment by sarkonovich** [comment]
Harry,

What's the server showing? On the Pitch....in the window you ran app.rb in?

**Comment by harrypottar** [comment]
Hi Steve,

Sorry didn’t see that, I tried to run bundle install again as per your instructions.

I really appreciate the time you’re spending on helping me

Thank
harry

 Errno::EACCES - Permission denied @ rb_sysopen - alexa_hue_user:
    /var/www/html/Alexa-Hue-master/hue_switch.rb:255:in `write'
    /var/www/html/Alexa-Hue-master/hue_switch.rb:255:in`authorize_user'
    /var/www/html/Alexa-Hue-master/hue_switch.rb:49:in `initialize'
    /var/www/html/Alexa-Hue-master/lights.rb:20:in`new'
    /var/www/html/Alexa-Hue-master/lights.rb:20:in `block in registered'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in`call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in`block (3 levels) in route!'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in`block (2 levels) in route!'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in`catch'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in`block in route!'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in`route!'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in`block in invoke'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in`invoke'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in`block in call!'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in`catch'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in`call!'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in`call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in`call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in`call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in`call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in`call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in`block in call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
    /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in`call'
    /usr/local/rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
    /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in`service'
    /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
    /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in`block in start_thread'
54.225.33.51 - - [28/Aug/2016:02:01:45 UTC] "POST /lights HTTP/1.1" 500 0

**Comment by sarkonovich** [comment]
Harry,

No problem. Happy to help.

So that is the output from bundle install? Try

sudo bundle install

Steve

**Comment by harrypottar** [comment]
Hi Steve,

Didn’t mean to confuse you, thats the output if I press the hub button and call the skill

I was reading your post https://github.com/sarkonovich/Alexa-Hue/blob/master/server_installation.md

And it said to try and reinstall, everything seems ok.

ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [armv7l-linux-eabihf]

if I try sudo bundle install it tells me it can not find it.

sudo bundle install
sudo: bundle: command not found

Thanks
harry

**Comment by harrypottar** [comment]
Hi Steve,

I found the issue, the program could no create the alexa_hue_user file, I manually created as the super user and then changed the permissions so it could read and write.

So far so good, thank you for all your help and a great program

Thanks

Harry

**Comment by sarkonovich** [comment]
On Sat, Aug 27, 2016 at 7:37 PM, harrypottar notifications@github.com
wrote:

> Hi Steve,
> 
> I found the issue, the program could no create the alexa_hue_user file, I
> manually created as the super user and then changed the permissions so it
> could read and write.
> 
> So far so good, thank you for all your help and a great program
> 
> Thanks
> 
> Harry

Harry,

That's great! I'll add something to the docs about making sure permissions
in the install directory are set correctly. Let me know if you have any
other questions!

Best,
Steve

**Comment by illperipherals** [comment]
Steve,
Mad props. That is quality tech support right there.

**Comment by sarkonovich** [comment]
Ha! Thanks...
