### ISSUE TITLE
Skills error

### ISSUE THREAD

**Issue by Head** [sarkonovich/Alexa-Hue#22]
**Intent Schema:**

> The intent schema is missing the following built-in intents: {"intent":"AMAZON.PauseIntent"}, {"intent":"AMAZON.ResumeIntent"}

**Sample Utterances:**

> Error: There was a problem with your request: Unknown slot type 'LIGHTS' for slot 'Lights'

**Comment by sarkonovich** [comment]
Is the error being generated because you have indicated that the skill uses audio player directives? Skills using those directives have to include those built-in intents. I don't think they are required for non-audio player skills.
