### ISSUE TITLE
Ruby unhappy with Alexa_Objects_rb

### ISSUE THREAD

**Issue by scottyell** [sarkonovich/Alexa-Hue#25]
Hey, sorry for making an 'issue' but I'm entirely unfamiliar with Ruby so really not sure where to start with the running error.

All installed fine on my Pi, then running ruby app.rb it throws out these errors?

http://pastebin.com/75kyEi0y

Advanced thanks!

**Comment by sarkonovich** [comment]
This is a Ruby version error. You need to be running 2.0 or above.

You can check the version by running ruby -v or, if you installed with RVM (Ruby Version Manager) type: rvm list
