### ISSUE TITLE
The remote endpoint could not be called, or the response it returned was invalid.

### ISSUE THREAD

**Issue by At0mM0nk3y** [sarkonovich/Alexa-Hue#27]
Hiya
So close to getting this to work......
If I ask to turn off front room lights then no problem (using the aws test function)
If I try to invoke a scene then I get the above error (same with light colours) - I downloaded all4hue and created the scene test that uses front room lights. I have also added test to the custom slot SCENE.
help me obi wan you're my only hope......

**Comment by sarkonovich** [comment]
Could you give me the server error you get?
Just write me back at sarkonovich at gmail dot com

Steve

**Comment by At0mM0nk3y** [comment]
cheers man for the swift reply.
issue was resolved by deleting vm and re-running docker quickstart terminal then updating lambda function with new url

**Comment by At0mM0nk3y** [comment]
Hi Steve,


Hope you're well and about to have a great new year.

Got it all working sweet but was wondering.......

If I'm honest a lot of what you've done is now handled by the philips hue skill - I have the old style hub - the new one handles setting scenes. Where I think your app would work going forward is voice commands for things like color loop. There are many apps that do light effects like fireworks and xmas etc. I wondered if you could point me in the right direction of creating these?


for what its worth ive included my settings for uk


to turn on a scene i use


tell philips turn on bedroom sunset.....

i have a scene called bedroom sunset in all4hue

i did try creating a scene called sunset with all lights attached but i found it flaky when trying to invoke turn on scene sunset in bedroom lights.


the other thing i changed which may be useful in your documentation is that i changed the lambda function timeout from 3000ms to 10000ms as it was giving skill timeout error (despite still working)




intent schema



{
  "intents": [
    {
      "intent": "AMAZON.StopIntent"

    },
    {
      "intent": "AMAZON.CancelIntent"

    },
    {
      "intent": "ListScenes",
      "slots":[]
    },
    {
      "intent": "ListGroups",
      "slots":[]
    },
    {
      "intent": "ListLights",
      "slots":[]
    },
    {
      "intent": "ControlLights",
      "slots": [
        {
          "name": "Lights",
          "type": "LIGHTS"
        },
        {
          "name": "Brightness",
          "type": "LEVEL"
        },
        {
          "name": "Saturation",
          "type": "LEVEL"
        },
        {
          "name": "State",
          "type": "STATE"
        },
                {
          "name": "Event",
          "type": "EVENT_TYPE"
        },
        {
          "name": "SaveScene",
          "type": "SAVESCENE"
        },
        {
          "name": "String",
          "type": "STRING"
        },
        {
          "name": "Color",
          "type": "COLOR"
        },
        {
          "name": "RelativeTime",
          "type": "AMAZON.DURATION"
        },
        {
          "name": "AbsoluteTime",
          "type": "AMAZON.TIME"
        },
        {
          "name": "Alert",
          "type": "ALERT_TYPE"
        },
        {
          "name": "Scene",
          "type": "SCENE"
        }
      ]
    }
  ]
}



custom slots


ALERT_TYPE

color loop

long alert

short alert


EVENT_TYPE

start

stop

turn on

turn off


STRING

ten minutes

twenty minutes

thirty minutes

half an hour


SAVESCENE

abc




All the best

Daz

________________________________

**Comment by sarkonovich** [comment]
Hello,

Honestly, I thought that this would have been fully supplanted a long time
ago.

However, as far as I know it still offers things that the hue skill doesn't:

Change the saturation
Set Timers/Alarms (e.g., "Flash the lights in five minutes", or "Set dinner
scene at 8pm")
Color loops/Flashes
Save Scenes

Or is Hue doing these things as well?

I would hope that this little app becomes useless soon!

Steve

**Comment by At0mM0nk3y** [comment]
Hiya

your little app is magic

Just being upfront with you....

As far as I know the hue skill turns lights on and off and sets brightness levels

For me this trumps your app as I say

alexa turn bedroom lights on....

alexa bedroom lights 100%

native apps do away with invocation names like ask philips etc

so i use them because its easier!

i would do away those on your app as there's no need.

yonomi does away with invocation also so i can say

all lights off

it is basic on the scenes! basic colours etc

where your app trumps them is that you can set time etc as you say but the color loop is fantastic.  your little app is brilliant - i think if you want to keep it alive i would remove the bits you dont need as it clashes with yonomi and hue eg: turn on bedroom lights. - build into it xmas / new year / valentines day /birthday / bonfire night scenes that you can set by date or built in. in the android store these sell for a few quid per xmas app / new year app. if u could build an android app that has the docker server built in and allows you to point the aws skill at it you'd make a fortune OR just add the flashing scenes by voice. Another brilliant add on would be the ability to run on a rasp pi and have a webcam change colours to what it sees on the cam.like the huey app did although this is defunct now. or even webcam on pc. i wouldnt give up with - theres a lot it can / could do.....


D



________________________________

**Comment by At0mM0nk3y** [comment]
Hi Steve,


Hope you're well.....

Was wondering if you knew a snazzy way of keeping the server with same settings after a reboot?


currently I do a kitematic start on the containers
then run docker quick start
then
docker-machine env
eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env)

then do the bash start
then update lambda with new ngrok io

is there a simpler way of getting it back without having to keep updating the lambda function?

(fingers n toes crossed)

All the best
D

________________________________

**Comment by sarkonovich** [comment]
Yes, there is. You can pay $5.00 a month for a dedicated ngrok tunnel, so
that whenever you start it up it uses the same address.
https://ngrok.com/product#pricing

You can also direct forward a port from your computer to the outside world
and skip ngrok all together (and assign a static ip address to your
computer.)
Either should work!

Steve

**Comment by At0mM0nk3y** [comment]
Hiya,


Forgive me for my complete ignorance but.....


So the server is running on a vm?

It has an ip of 192.168.x.x:32768


So I can change the lambda passthrough to my external ip address and then on my router port forward to

192.168.x.x?


D


________________________________

**Comment by sarkonovich** [comment]
Yes. I think that should work!

Steve

**Comment by At0mM0nk3y** [comment]
Hiya,


So the only thing I would need to do after a reboot would be

make sure default vm is running and start Docker-Alexa-Hue

I can delete the ngrok containers and just have docker-alexa-hue on its own?

Cheers for your help btw it is very much appreciated........


D

________________________________
