### ISSUE TITLE
Error starting server?

### ISSUE THREAD

**Issue by cricenog** [sarkonovich/Alexa-Hue#3]
Hello, I'm so excited to get this working, but I'm having an issue starting the server - I installed the Ruby 2.2.0 via rpm on my rpi, did the bundle install, and then did ruby app.rb, but I receive the following:

/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- sinatra/base (LoadError)
    from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from app.rb:1:in `<main>'

I'm installing Sinatra now incase that is the issue, but if not, any other ideas? Thanks!

Thank you!

**Comment by sarkonovich** [comment]
Hello! Happy to help.

It looks like you don't have Sinatra installed. Try

gem install sinatra

in a terminal window.

Let me know if that helps....
Steve

**Comment by cricenog** [comment]
Cool it's installing now!! Thank you! Quick question while I have your attention - the doc readme states:

Before you can use the skill, you'll need to give it access to your Hue bridge. Press the link button on your bridge and launch the skill (within, I think, 20 seconds or so.) 

What do you mean by launching the skill? Is that just invoking a command with the echo? Or is that something on the server or with AWS/Lamba?

Thank you!!

**Comment by sarkonovich** [comment]
Great.

Just out of curiosity, did the command 'bundle install' not install
sinatra?  (I might have to go fix that...)

So, I mean before you launch the skill with the Echo. If you say, "Alexa,
launch house lighting (or 'hue'...or whatever you decided to call it) Alexa
should say something like, "You'll need to press the link button on your
bridge...."

Steve

**Comment by sarkonovich** [comment]
Yes....Gemfile is missing sinatra. Will fix. Thank you!

**Comment by cricenog** [comment]
Thank you!!!

**Comment by cricenog** [comment]
Any other gems missing? More errors:

root@raspberrypi:/home/pi/AlexaHue/Alexa-Hue-master# ruby app.rb
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:79: syntax error, unexpected ':', expecting => (SyntaxError)
                      "version": "2.0",
                                ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:79: syntax error, unexpected ',', expecting keyword_end
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:80: syntax error, unexpected ':', expecting keyword_end
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:82: syntax error, unexpected ':', expecting :: or '[' or '.'
                        "response": {
                                   ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:83: syntax error, unexpected ':', expecting =>
                          "outputSpeech": {
                                         ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:84: syntax error, unexpected ':', expecting =>
                            "type": speech_type,
                                   ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:85: syntax error, unexpected ':', expecting :: or '[' or '.'
                            "#{text_type}": spoken_response
                                           ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:87: syntax error, unexpected ':', expecting keyword_end
                          "card": {
                                 ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:88: syntax error, unexpected ':', expecting =>
                            "type": "Simple",
                                   ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:88: syntax error, unexpected ',', expecting keyword_end
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:89: syntax error, unexpected ':', expecting keyword_end
                            "title": card_title,
                                    ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:90: syntax error, unexpected ':', expecting :: or '[' or '.'
                            "content": card_content
                                      ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:92: syntax error, unexpected ':', expecting keyword_end
                      "reprompt": {
                                 ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:93: syntax error, unexpected ':', expecting =>
                        "outputSpeech": {
                                       ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:94: syntax error, unexpected ':', expecting =>
                          "type": speech_type,
                                 ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:95: syntax error, unexpected ':', expecting :: or '[' or '.'
                          "text": reprompt_text
                                 ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:98: syntax error, unexpected ':', expecting keyword_end
                      "shouldEndSession": end_session 
                                         ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:104: syntax error, unexpected ':', expecting =>
...hs[:response][:card] = {"type": "LinkAccount"} }
...                               ^
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:104: syntax error, unexpected '}', expecting keyword_end
/home/pi/AlexaHue/Alexa-Hue-master/alexa_objects.rb:112: syntax error, unexpected end-of-input, expecting keyword_end
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from app.rb:3:in `<main>'

thanks!!

**Comment by cricenog** [comment]
I read from Google potentially - gem install mechanize ?

**Comment by sarkonovich** [comment]
No, not a gem error. A syntax error. It's missing an apostrophe or comma.
Give me just a couple of minutes.

Steve

**Comment by sarkonovich** [comment]
Actually, it's fine.  Maybe you're not running version 2.0 of ruby or
above. What do you get when you type

ruby --version

in a terminal window?

Steve

**Comment by cricenog** [comment]
ruby 2.1.5p273 (2014-11-13) [arm-linux-gnueabihf]

**Comment by sarkonovich** [comment]
Weird. I just downloaded the copy from Github and it runs fine.

Okay, what if you type

ruby -cw alexa_objects.rb

in the terminal?

**Comment by cricenog** [comment]
Weird..similar syntax errors:

root@raspberrypi:/home/pi/AlexaHue/Alexa-Hue-master# ruby -cs alexa_objects.rb
alexa_objects.rb:79: syntax error, unexpected ':', expecting =>
                      "version": "2.0",
                                ^
alexa_objects.rb:79: syntax error, unexpected ',', expecting keyword_end
alexa_objects.rb:80: syntax error, unexpected ':', expecting keyword_end
alexa_objects.rb:82: syntax error, unexpected ':', expecting :: or '[' or '.'
                        "response": {
                                   ^
alexa_objects.rb:83: syntax error, unexpected ':', expecting =>
                          "outputSpeech": {
                                         ^
alexa_objects.rb:84: syntax error, unexpected ':', expecting =>
                            "type": speech_type,
                                   ^
alexa_objects.rb:85: syntax error, unexpected ':', expecting :: or '[' or '.'
                            "#{text_type}": spoken_response
                                           ^
alexa_objects.rb:87: syntax error, unexpected ':', expecting keyword_end
                          "card": {
                                 ^
alexa_objects.rb:88: syntax error, unexpected ':', expecting =>
                            "type": "Simple",
                                   ^
alexa_objects.rb:88: syntax error, unexpected ',', expecting keyword_end
alexa_objects.rb:89: syntax error, unexpected ':', expecting keyword_end
                            "title": card_title,
                                    ^
alexa_objects.rb:90: syntax error, unexpected ':', expecting :: or '[' or '.'
                            "content": card_content
                                      ^
alexa_objects.rb:92: syntax error, unexpected ':', expecting keyword_end
                      "reprompt": {
                                 ^
alexa_objects.rb:93: syntax error, unexpected ':', expecting =>
                        "outputSpeech": {
                                       ^
alexa_objects.rb:94: syntax error, unexpected ':', expecting =>
                          "type": speech_type,
                                 ^
alexa_objects.rb:95: syntax error, unexpected ':', expecting :: or '[' or '.'
                          "text": reprompt_text
                                 ^
alexa_objects.rb:98: syntax error, unexpected ':', expecting keyword_end
                      "shouldEndSession": end_session 
                                         ^
alexa_objects.rb:104: syntax error, unexpected ':', expecting =>
...hs[:response][:card] = {"type": "LinkAccount"} }
...                               ^
alexa_objects.rb:104: syntax error, unexpected '}', expecting keyword_end
alexa_objects.rb:112: syntax error, unexpected end-of-input, expecting keyword_end
root@raspberrypi:/home/pi/AlexaHue/Alexa-Hue-master#

**Comment by cricenog** [comment]
One thing I may have missed when installing rvm is giving root access to it? I read you have to do:

sudo adduser admin rvm

Thoughts?

Thanks,

**Comment by sarkonovich** [comment]
That's what I expected. But I can't figure out why given that you're
running 2.1.

Give me a second...

Steve

**Comment by sarkonovich** [comment]
Don't know. Generally, you're not suppose to use sudo with rvm. I'm 99%
it's a version issue.  Try this:

rvm list

and tell me what you get

Steve

**Comment by cricenog** [comment]
Eek, 

bash: rvm: command not found

**Comment by sarkonovich** [comment]
Hmm. Still....

And what if you type this:

gem env

(and write be back at sarkonovich@gmail.com)
