### ISSUE TITLE
Timer/Scheduler problem

### ISSUE THREAD

**Issue by ghost** [sarkonovich/Alexa-Hue#5]
I think I figured out why my timer's don't seem to work correctly...

It looks like you convert relative timers ("in 15 seconds") into absolute times by adding the "adder" to the current time. but that current time is the PCs localtime... and if there is any discrepancy between the server's localtime and the Hue Bridge's system time, then the timer won't go off at the "right time".

Just to drive the point home, say my box is running one minute ahead of the bridge... then when I say "do X in 20 seconds" (and the ruby server has local time 12:00:00), the schedule will be set for the time 12:00:20. But if the Hue Bridge's time is 1 minute behind (at 11:59:00) at the time it receives the request, then the timer won't be triggered for a full minute after one would expect it to trigger... Worse yet, I'm pretty sure if the local machine's system clock is running BEHIND the hue bridge, then the timers may end up scheduled in "the past" as far as the bridge is concerned... leading to more unstable behavior. (perceived as buggy by users)

As I doubt the Hue bridge actually allows relative schedules to be set, maybe there is a way to pull the time from the bridge, and use that time as the base instead of the local box's system clock...  (Good chance the Hue bridge is just using whatever time the wifi router tells it (I haven't looked, but seems like a good guess)) 

If that fails, then perhaps there's a way to derive the delta between the local machine's system time and the hue bridge's time (some kind of training? maybe the user can be involved if it comes to it), and just store that off and correct for that whenever timers are set... (not ideal...)

I'll keep playing with it, but I figured I'd at least bring it up.. seeing as it takes much less time to find issues and even isolate them... than it does to fix them! (and I'm always short on time...)

**Comment by sarkonovich** [comment]
Awesome. That's a good catch.

Actually, it looks like the Hue API does allow you to set timers with
relative time, so I'll do that instead of incrementing the current time.
 (The skill currently does check if you've scheduled the timer "in the
past", relative to the bridge. Alexa should tell you that you've done that.)

I'll fix these soon.

Thanks again.

Steve

**Comment by sarkonovich** [comment]
Fixed. Timers (relative time schedules) now set relative to time on bridge.
