### ISSUE TITLE
setting light timers gives an error

### ISSUE THREAD

**Issue by jswineheart** [sarkonovich/Alexa-Hue#9]
I recently ran though this and got it working except for the timer or alarm functions. She says "youve set the schedule to a time in the past" every time. Im looking though the code and I can't find a reason for it.

I am using this version of the repo, I have installed the jpeffer docker container on a windows box. 
All times are in sync between amazon, Alexa, computer, and vm

**Comment by sarkonovich** [comment]
Okay. Let me look into it. Could you just verify that this error occurs:

a) for a 5 minute timer  ("turn of the [whatever] lights in 5 minutes")

b) for a 2 hour timer ("turn of the [whatever] lights in two hours")

c) an alarm  ("turn on the [whatever] lights at 8 p.m."   -- any time in the future)

Also, any chance you could tell me what you get when you open a terminal window and type:
TIME /T

and what the hue bridge config info is? (That thing I asked you to check on Youtube:
http://your_bridge_ip_address/debug/clip.html

and then, 

/api/1234567890/config 

It might take be a bit to track this down, but I'll update here!
Steve

**Comment by jswineheart** [comment]
a) "youve set the schedule to a time in the past"
b) "youve set the schedule to a time in the past"
c) worked and confirmed 20:00 hours

TERMINAL RESPONSE:
10:57 AM

BRIDGE CONFIG INFO:
{
    "name": "Philips hue",
    "zigbeechannel": 15,
    "bridgeid": "001788FFFE260FFD",
    "mac": "00:17:88:26:0f:fd",
    "dhcp": true,
    "ipaddress": "192.168.0.103",
    "netmask": "255.255.255.0",
    "gateway": "192.168.0.1",
    "proxyaddress": "none",
    "proxyport": 0,
    "UTC": "2016-04-09T14:57:08",
    "localtime": "2016-04-09T10:57:08",
    "timezone": "America/Indiana/Indianapolis",
    "modelid": "BSB002",
    "swversion": "01031131",
    "apiversion": "1.12.0",
    "swupdate": {
        "updatestate": 0,
        "checkforupdate": false,
        "devicetypes": {
            "bridge": false,
            "lights": [],
            "sensors": []
        },
        "url": "",
        "text": "",
        "notify": false
    },
    "linkbutton": false,
    "portalservices": true,
    "portalconnection": "connected",
    "portalstate": {
        "signedon": true,
        "incoming": true,
        "outgoing": true,
        "communication": "disconnected"
    },
    "factorynew": false,
    "replacesbridgeid": null,
    "backup": {
        "status": "idle",
        "errorcode": 0
    },
    "whitelist": {
        "1234567890": {
            "last use date": "2016-04-09T14:57:08",
            "create date": "2016-04-09T06:12:39",
            "name": "Hue_Switch"
        },
        "c0fc22d57cecdd55490eee7402b9a7e": {
            "last use date": "2016-03-18T20:22:49",
            "create date": "2016-03-18T18:57:30",
            "name": "Hue#Asus Nexus 7"
        },
        "go7bzK16e5PlDpFtcCqmcCFGzQX8Kk9F3rJeEirh": {
            "last use date": "2016-04-08T18:41:01",
            "create date": "2016-03-18T20:06:27",
            "name": "Hue#Samsung SAMSUNG-SGH"
        },
        "Lunj0u9mkAiRQ-9qFGqnUYbyzQP2pFgLsvze3ac1": {
            "last use date": "2016-03-30T20:22:52",
            "create date": "2016-03-30T20:13:08",
            "name": "Echo"
        },
        "e0XoJknulHfmpSbVzAc7H3hcBrP90UtxLhdZYmot": {
            "last use date": "2016-04-09T14:11:01",
            "create date": "2016-03-30T20:13:08",
            "name": "Echo"
        },
        "oiTORyja6u4wHwbmDoyRhSPmOpK92ql0c7dHvVl2": {
            "last use date": "2016-04-09T01:11:01",
            "create date": "2016-04-05T01:28:24",
            "name": "Hue#Asus Nexus 7"
        },
        "PLjJjFxwzDY2Kvtm29-ZrkcqDnyedoQPFzT3LIS3": {
            "last use date": "2016-04-05T18:07:53",
            "create date": "2016-04-05T17:16:57",
            "name": "MyApplication#AnyMote Smart Remot"
        },
        "CR6h6Vvvzb8XiziEbvvVXU13FwEkk1TZpAYlHlRA": {
            "last use date": "2016-04-06T12:56:01",
            "create date": "2016-04-06T12:21:22",
            "name": "MyApplication#AnyMote Smart Remot"
        },
        "hPI32pdX2R8bwLZDV0v8Czu5anzqSHTu1baIaHmJ": {
            "last use date": "2016-04-09T14:57:08",
            "create date": "2016-04-07T19:44:32",
            "name": "Harmony Hub"
        },
        "26JOtHCn2jc3miInbAIZvjaI1-PsN39drE5SXMCR": {
            "last use date": "2016-04-09T03:11:01",
            "create date": "2016-04-08T18:35:22",
            "name": "Hue#Samsung SAMSUNG-SGH"
        },
        "Mm1QUbepIv0ZCQlwN1-rS96Jwq-C6mWlKI-WoAXV": {
            "last use date": "2016-04-09T14:56:01",
            "create date": "2016-04-09T14:30:14",
            "name": "all 4 hue#SAMSUNG-SGH-I537"
        }
    }
}

**Comment by jswineheart** [comment]
Its almost like its not recognizing relative time:
Heres what in my settings, just to confirm I have added the below

FROM INTENT
        {
          "name": "RelativeTime",
          "type": "AMAZON.DURATION"
        },
        {
          "name": "AbsoluteTime",
          "type": "AMAZON.TIME"
        },

FROM SAMPLE UTTERANCES:
ControlLights turn {State} the {Lights} in {AbsoluteTime}
ControlLights turn the {Lights} {State} in {AbsoluteTime}
ControlLights turn the {Lights} {Color} in {AbsoluteTime}
ControlLights turn the {Lights} to {Color} in {AbsoluteTime}
ControlLights turn the {Lights} to the {Color} in {AbsoluteTime}
ControlLights change the {Lights} to {Color} in {AbsoluteTime}
ControlLights change the {Lights} to the {Color} in {AbsoluteTime}
ControlLights set the {Lights} to {Color} in {AbsoluteTime}
ControlLights set the {Lights} to the {Color} in {AbsoluteTime}

ControlLights turn {State} the {Lights} at {RelativeTime}
ControlLights turn the {Lights} {State} at {RelativeTime}
ControlLights turn the {Lights} {Color} at {RelativeTime}
ControlLights turn the {Lights} to {Color} at {RelativeTime}
ControlLights turn the {Lights} to the {Color} at {RelativeTime}
ControlLights change the {Lights} to {Color} at {RelativeTime}
ControlLights change the {Lights} to the {Color} at {RelativeTime}
ControlLights set the {Lights} to {Color} at {RelativeTime}
ControlLights set the {Lights} to the {Color} at {RelativeTime}
ControlLights turn {State} {Lights} in {RelativeTime}
ControlLights turn {State} {Lights} at {AbsoluteTime}

**Comment by jswineheart** [comment]
interesting: 
I noticed my UTC is 4 hours ahead, and asked ("turn of the [whatever] lights in four and a half hours") and it set it for 15:32 hours.

**Comment by jswineheart** [comment]
I set a couple more than 4 hours in advance and they seem to work, and using all 4 hue, I am able to see them as alarms however they are triggering "all lights" instead of the specific light I asked for and are indeed 4 hours out.

in further testing, if I ask for a timer at 4 hours, it fails but 4 hours 1 second its good, it has to be something with the UTC vs EST

**Comment by jswineheart** [comment]
What device is determining Time.now, is that the windows machine/vm/or amazon?

def schedule (string)
      set_time = Time.parse(string).to_s.sub(' ', 'T').rpartition(' ').first
      p set_time
      if Time.parse(string) < Time.now
        "You've set the schedule to a time in the past. Please indicate a.m. or p.m. when specifying a time."
      else
        self.schedule_params = {:name=>"Hue_Switch Alarm",
               :description=>"",
               :localtime=>"#{set_time}",
               :status=>"enabled",
               :autodelete=>true
              }
              p self.schedule_params
        if self.lights_array.any?
          lights_array.each do |l|
            self.schedule_params[:command] = {:address=>"/api/#{@user}/lights/#{l}/state", :method=>"PUT", :body=>self.body}
          end
        else
          self.schedule_params[:command] = {:address=>"/api/#{@user}/groups/#{self._group}/action", :method=>"PUT", :body=>self.body}
        end
        p self.schedule_params
        self.schedule_ids.push(HTTParty.post("http://#{@ip}/api/#{@user}/schedules", :body => (self.schedule_params).to_json))

```
    if self.schedule_ids.flatten.last.include?("success")
      "Schedule set at #{Time.parse(set_time).strftime("%H:%M")}"
    else
      "Scheduling error. Schedule not set"
    end
  end
end
```

**Comment by sarkonovich** [comment]
The timers/alarms all show up as affecting all light on these apps, but they should only affect the requested lights. 

There are actually two things. Timers ("turn off the lights in 5 minutes") are set relative to times on the bridge. Alarms are still set relative to the time on the server. So, yeah, if the server is +4 relative to the bridge, that's going to trigger the "you've set this alarm to a time in the past" message.

What about timers?  Do you get that message with them?

**Comment by sarkonovich** [comment]
> > What device is determining Time.now, is that the windows machine/vm/or amazon?

Time.now is time on the server. Sounds like that time is ahead of the bridge time.
For timers ('in 5 minutes') -- that's all done relative to bridge time.
But it didn't make sense to set alarms relative to that time, since, if there's a misalignment, the alarm wouldn't go off when you thought it would.

**Comment by jswineheart** [comment]
what command specifically uses a timer vs alarm?

**Comment by sarkonovich** [comment]
Timers use the commands like  "in 5 minutes/hours/days"

"Alexa, tell [invocation name] to turn on the kitchen lights in 10 minutes."

Alarms use absolute times, e.g., at 8:00 p.m.

"Alexa, tell [invocation name] to turn on the kitchen lights at 8:00 p.m."

The bridge time looks right, i.e., the time zone is UTC -4 hours (which is EDT.) So, I bet the server hasn't been setup with the correct local  time zone, and is using UTC.  (I suppose this could be a docker issue, but I'd think the docker container would use the same time zone as the machine it's running on.)

Steve

**Comment by sarkonovich** [comment]
I will set up a docker container and try to see why the relative time isn't working. It should since it's independent entirely of the server time!

Steve

**Comment by jswineheart** [comment]
Im willing to bet something went wrong when I was setting up the server, I just noticed the windows box was not set to update its time automatically so despite having the correct time, i have no idea what time zone it thought it was in. I am going to try and reset the time zone info and whatnot in the VM along with getting the windows box corrected and see if that works, if not I may just wipe the VM and make a new one.
Thanks for all the help!! I really appreciate it

**Comment by jswineheart** [comment]
This is some really great and interesting code

**Comment by jswineheart** [comment]
OK, I'm once again at a loss. I can see the server things its in UTC and tried setting it to EDT, America/Indianapolis, America/Indiana/Indianapolis, EST, whatever... and its still not working.

Ive verified the windows box is getting its time and date automatically and is set in the correct time zone and reloaded the MINGW64 Docker from the ground up. Still everything works fine except the timer

**Comment by sarkonovich** [comment]
Hmm. I'm sort of running around today, I'll have more time tomorrow. I wonder if there's a docker setting. The docker thing is totally new to me...someone else set up it. But, if you want to poke around more -- though it's sounds like you've done a lot -- that's where I'd look. I'll do that tomorrow!

Thanks for investigating. It really helps me to get this thing ironed out.

Oh, and you might check with pfeffer...he might know more about the docker settings.

**Comment by sarkonovich** [comment]
It's a problem with the Docker container. It's using the base system default of UTC instead of syncing to host.  For now, this should fix it. Close the container and run again using this command:

docker run -e "TZ=America/Indiana/Indianapolis" -itdP --name=docker-alexa-hue jpeffer/docker-alexa-hue

Let me know if this works! 

I'll work on getting a general fix out.

**Comment by jswineheart** [comment]
You beat me too it, I was just looking for that same work around. I noticed when starting the VM it showed the UTC time and the timestamp 4 hours ahead (for me anyways) and any time i try to reset it, the docker just put it back.

I had given up for the night, saw your response and had to try it out. Can confirm adding the TZ in the run worked!! I now have full use of my Hue lights just in time to turn them all off and go to bed. Maybe Ill give myself a quick timer see if i can get there before they go out. LOL

Thanks for the help and learning experience!
